//  generated by test_genlist.py

#if defined(RACCOON_128_1)
#define RACC_(s)    RACCOON_128_1_##s
#define RACC_NAME   "Raccoon-128-1"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    8
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      1
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  14800
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_128_2)
#define RACC_(s)    RACCOON_128_2_##s
#define RACC_NAME   "Raccoon-128-2"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      2
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  14816
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_128_4)
#define RACC_(s)    RACCOON_128_4_##s
#define RACC_NAME   "Raccoon-128-4"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      4
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  14848
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_128_8)
#define RACC_(s)    RACCOON_128_8_##s
#define RACC_NAME   "Raccoon-128-8"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     5
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      8
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  14912
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_128_16)
#define RACC_(s)    RACCOON_128_16_##s
#define RACC_NAME   "Raccoon-128-16"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     5
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      16
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  15040
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_128_32)
#define RACC_(s)    RACCOON_128_32_##s
#define RACC_NAME   "Raccoon-128-32"
#define RACC_KAPPA  128
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     4
#define RACC_UW     39
#define RACC_N      512
#define RACC_K      5
#define RACC_ELL    4
#define RACC_W      19
#define RACC_D      32
#define RACC_B22    14656575897
#define RACC_BOO    41954689765971
#define RACC_PK_SZ  2256
#define RACC_SK_SZ  15296
#define RACC_SIG_SZ 11524
#endif

#if defined(RACCOON_192_1)
#define RACC_(s)    RACCOON_192_1_##s
#define RACC_NAME   "Raccoon-192-1"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    8
#define RACC_UT     7
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      1
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  18840
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_192_2)
#define RACC_(s)    RACCOON_192_2_##s
#define RACC_NAME   "Raccoon-192-2"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     7
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      2
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  18864
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_192_4)
#define RACC_(s)    RACCOON_192_4_##s
#define RACC_NAME   "Raccoon-192-4"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     7
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      4
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  18912
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_192_8)
#define RACC_(s)    RACCOON_192_8_##s
#define RACC_NAME   "Raccoon-192-8"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     6
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      8
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  19008
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_192_16)
#define RACC_(s)    RACCOON_192_16_##s
#define RACC_NAME   "Raccoon-192-16"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     6
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      16
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  19200
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_192_32)
#define RACC_(s)    RACCOON_192_32_##s
#define RACC_NAME   "Raccoon-192-32"
#define RACC_KAPPA  192
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     5
#define RACC_UW     39
#define RACC_N      512
#define RACC_K      7
#define RACC_ELL    5
#define RACC_W      31
#define RACC_D      32
#define RACC_B22    24964497408
#define RACC_BOO    47419426657048
#define RACC_PK_SZ  3160
#define RACC_SK_SZ  19584
#define RACC_SIG_SZ 14544
#endif

#if defined(RACCOON_256_1)
#define RACC_(s)    RACCOON_256_1_##s
#define RACC_NAME   "Raccoon-256-1"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    8
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      1
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  26016
#define RACC_SIG_SZ 20330
#endif

#if defined(RACCOON_256_2)
#define RACC_(s)    RACCOON_256_2_##s
#define RACC_NAME   "Raccoon-256-2"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      2
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  26048
#define RACC_SIG_SZ 20330
#endif

#if defined(RACCOON_256_4)
#define RACC_(s)    RACCOON_256_4_##s
#define RACC_NAME   "Raccoon-256-4"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     6
#define RACC_UW     41
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      4
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  26112
#define RACC_SIG_SZ 20330
#endif

#if defined(RACCOON_256_8)
#define RACC_(s)    RACCOON_256_8_##s
#define RACC_NAME   "Raccoon-256-8"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     5
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      8
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  26240
#define RACC_SIG_SZ 20330
#endif

#if defined(RACCOON_256_16)
#define RACC_(s)    RACCOON_256_16_##s
#define RACC_NAME   "Raccoon-256-16"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    2
#define RACC_UT     5
#define RACC_UW     40
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      16
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  26496
#define RACC_SIG_SZ 20330
#endif

#if defined(RACCOON_256_32)
#define RACC_(s)    RACCOON_256_32_##s
#define RACC_NAME   "Raccoon-256-32"
#define RACC_KAPPA  256
#define RACC_Q      549824583172097
#define RACC_NUT    42
#define RACC_NUW    44
#define RACC_REP    4
#define RACC_UT     4
#define RACC_UW     39
#define RACC_N      512
#define RACC_K      9
#define RACC_ELL    7
#define RACC_W      44
#define RACC_D      32
#define RACC_B22    38439957299
#define RACC_BOO    50958538642039
#define RACC_PK_SZ  4064
#define RACC_SK_SZ  27008
#define RACC_SIG_SZ 20330
#endif
